apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-ebs-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2  # or ebs-sc depending on your setup
